# Generated by Django 3.2.5 on 2022-05-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertedindex',
            name='term',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
