# Generated by Django 3.2.5 on 2022-05-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_invertedindex_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
